<a href="https://colab.research.google.com/github/dgalian/FTW_B7/blob/main/Capstone/Capstone_MBA_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Using Market Basket Analysis to determine the typical combination of ICD Categories per Claim**

# Import libraries and load dataset

In [1]:
# Importing
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# Load claims breakdown by diagnosis
clm_icd = pd.read_csv('/content/CLM Breakdown csv.csv')

In [3]:
# Load ICD table
icd_table = pd.read_excel('/content/icd_table.xlsx')

# Data Prep
Profiling, Cleaning

In [4]:
icd_table.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4343 entries, 0 to 4342
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   icdno        4343 non-null   int64 
 1   icdcategory  4343 non-null   int64 
 2   icdgroup     4343 non-null   int64 
 3   ICD CODE     4343 non-null   object
 4   ICD DISEASE  4343 non-null   object
dtypes: int64(3), object(2)
memory usage: 169.8+ KB


In [5]:
# Creating basket of claims
claims = pd.merge(clm_icd, icd_table, on='icdno', how='left')

In [6]:
claims.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 382438 entries, 0 to 382437
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   cbdcode        382438 non-null  int64  
 1   claimcode      382438 non-null  int64  
 2   icdno          382438 non-null  int64  
 3   doctorcode     382438 non-null  int64  
 4   cptno          382438 non-null  int64  
 5   sacode         382438 non-null  int64  
 6   UNIT AMT       382438 non-null  float64
 7   QTY            382438 non-null  float64
 8   INCURRED AMT   382438 non-null  float64
 9   HOSP BILL AMT  382438 non-null  float64
 10  COVERED AMT    382438 non-null  float64
 11  BILL TO        382438 non-null  object 
 12  icdcategory    382355 non-null  float64
 13  icdgroup       382355 non-null  float64
 14  ICD CODE       382355 non-null  object 
 15  ICD DISEASE    382355 non-null  object 
dtypes: float64(7), int64(6), object(3)
memory usage: 49.6+ MB


In [7]:
claims.isnull().sum()

cbdcode           0
claimcode         0
icdno             0
doctorcode        0
cptno             0
sacode            0
UNIT AMT          0
QTY               0
INCURRED AMT      0
HOSP BILL AMT     0
COVERED AMT       0
BILL TO           0
icdcategory      83
icdgroup         83
ICD CODE         83
ICD DISEASE      83
dtype: int64

In [8]:
# Drop null values
claims = claims.dropna()
claims.isnull().sum()

cbdcode          0
claimcode        0
icdno            0
doctorcode       0
cptno            0
sacode           0
UNIT AMT         0
QTY              0
INCURRED AMT     0
HOSP BILL AMT    0
COVERED AMT      0
BILL TO          0
icdcategory      0
icdgroup         0
ICD CODE         0
ICD DISEASE      0
dtype: int64

In [9]:
# Convert Claim code and ICD Category into categorical data
claims['claimcode'] = claims['claimcode'].astype(str)
claims['icdcategory'] = claims['icdcategory'].astype(int).astype(str)

In [10]:
# Drop other columns
claims = claims[['claimcode','icdno','icdcategory','ICD CODE','ICD DISEASE']]
claims[200:260]

claimcode  icdno icdcategory ICD CODE  \
200    209969  29838         227    S61.2   
201    209969  29838         227    S61.2   
202    209969  29838         227    S61.2   
203    209972  29838         227    S61.2   
204    209976   3645          53    E04.9   
205    210033  21009         169    N39.0   
206    210037   1834          24    C50.9   
207    210046   1834          24    C50.9   
208    210046   1834          24    C50.9   
209    210046   1834          24    C50.9   
210    210054  46082         108      I64   
211    210062   3645          53    E04.9   
212    210066  10084         104    I11.9   
213    210066  10084         104    I11.9   
214    210066  10084         104    I11.9   
215    210317  21023         170      N40   
216    210317  21023         170      N40   
217    210317  21023         170      N40   
218    210317  21023         170      N40   
219    210317  21023         170      N40   
220    210317  21023         170      N40   
221    210317  21023         170      N40   
222    210317  21023         170      N40   
223    210317  21023         170      N40   
224    210317  21023         170      N40   
225    210317  21023         170      N40   
226    210317  21023         170      N40   
227    210343  45847          55      E14   
228    210345  32087         229  S82.152   
229    210346  15693         145    M17.9   
230    210379   5378          71    F84.0   
231    210382  76619         104    I10.9   
232    210382  76619         104    I10.9   
233    210383   5378          71    F84.0   
234    210387   5378          71    F84.0   
235    210391   5378          71    F84.0   
236    210393   5378          71    F84.0   
237    210396  11788         115    J33.9   
238    210396  11788         115    J33.9   
239    210398   5378          71    F84.0   
240    210400   5378          71    F84.0   
241    210417  10341         107    I49.9   
242    210417  10341         107    I49.9   
243    210417  10341         107    I49.9   
244    210417  10341         107    I49.9   
245    210417  10341         107    I49.9   
246    210447  44878         231    T79.3   
247    210447  44878         231    T79.3   
248    210447  44878         231    T79.3   
249    210498   3213          44    D39.1   
250    210501  76619         104    I10.9   
251    210503   4386          61    E79.0   
252    210503   4386          61    E79.0   
253    210503   4386          61    E79.0   
254    210528  34061         235      T22   
255    210528  34061         235      T22   
256    210528  34061         235      T22   
257    210528  34061         235      T22   
258    210528  34061         235      T22   
262    210556  40054         261      W55   

                                           ICD DISEASE  
200  Open wound of other finger without damage to nail  
201  Open wound of other finger without damage to nail  
202  Open wound of other finger without damage to nail  
203  Open wound of other finger without damage to nail  
204                       Nontoxic goiter, unspecified  
205        Urinary tract infection, site not specified  
206   Malignant neoplasm of breast of unspecified site  
207   Malignant neoplasm of breast of unspecified site  
208   Malignant neoplasm of breast of unspecified site  
209   Malignant neoplasm of breast of unspecified site  
210  Stroke, not specified as haemorrhage or infarc...  
211                       Nontoxic goiter, unspecified  
212   Hypertensive heart disease without heart failure  
213   Hypertensive heart disease without heart failure  
214   Hypertensive heart disease without heart failure  
215                                  Enlarged prostate  
216                                  Enlarged prostate  
217                                  Enlarged prostate  
218                                  Enlarged prostate  
219                                  Enlarged prostate  
220                                  Enlarged prostate  
221 

In [11]:
claims[claims['claimcode']=='203913']

claimcode  icdno icdcategory ICD CODE                 ICD DISEASE
1    203913  40054         261      W55  Contact with other mammals
2    203913  40054         261      W55  Contact with other mammals
3    203913  40054         261      W55  Contact with other mammals
4    203913  40054         261      W55  Contact with other mammals
5    203913  40054         261      W55  Contact with other mammals
6    203913  40054         261      W55  Contact with other mammals

In [12]:
claims['icdcategory'].nunique()

241

In [13]:
# Removing duplicate ICD categories in claims, since we are only looking at the occurance of the ICD category per claim
claims['claims_icd'] = claims[['claimcode', 'icdcategory']].agg('_'.join, axis=1)
claims_icd = claims.drop_duplicates(subset='claims_icd')

In [14]:
# Checking number of ICD categories per claim
claims_icd['claimcode'].value_counts().sort_values(ascending=False)

328555    10
309069    10
305146    10
434764     9
377387     9
          ..
452895     1
452897     1
452902     1
452903     1
658022     1
Name: claimcode, Length: 166947, dtype: int64

In [15]:
claims_icd[claims_icd['claimcode']=='328555']

claimcode  icdno icdcategory ICD CODE  \
201183    328555  12785         130    K76.0   
201184    328555  46010         158    M81.9   
201186    328555  25106         216    R80.9   
201188    328555   3857          54      E11   
201189    328555  14648         144    M06.9   
201190    328555   4467          61    E87.8   
201191    328555   3639          53    E03.9   
201192    328555  20895         167    N20.9   
201193    328555  10140         105    I25.1   
201195    328555  10341         107    I49.9   

                                              ICD DISEASE  claims_icd  
201183  Fatty (change of) liver, not elsewhere classified  328555_130  
201184                          Osteoporosis, unspecified  328555_158  
201186                           Proteinuria, unspecified  328555_216  
201188                           Type 2 diabetes mellitus   328555_54  
201189                  Rheumatoid arthritis, unspecified  328555_144  
201190  Other disorders of electrolyte and fluid balan...   328555_61  
201191                        Hypothyroidism, unspecified   328555_53  
201192                      Urinary calculus, unspecified  328555_167  
201193  Atherosclerotic heart disease of native corona...  328555_105  
201195                    Cardiac arrhythmia, unspecified  328555_107

In [16]:
# Considering only claims with 2 or more ICD categories
claims_icdcombo = claims_icd.groupby('claimcode').filter(lambda x : x['claimcode'].shape[0]>1)
claims_icdcombo['claimcode'].value_counts().sum()

38603

In [17]:
38603/166947

0.23122907269971907

38,603 out of 166,947 or 23% of the claims has 2 or more ICD categories.

# MBA #1: Algorithms from DataCamp

## Preparing Transaction List

In [100]:
# Get list ICD Categories by Claim number
transactions = claims_icdcombo.groupby('claimcode').agg(lambda col: ','.join(col)).reset_index()
transactions

/usr/local/lib/python3.8/dist-packages/pandas/core/groupby/generic.py:303: FutureWarning: Dropping invalid columns in SeriesGroupBy.agg is deprecated. In a future version, a TypeError will be raised. Before calling .agg, select only columns which should be valid for the aggregating function.
  results[key] = self.aggregate(func)


claimcode      icdcategory  \
0        220945          113,169   
1        220946       104,54,113   
2        230470        53,54,105   
3        232051       169,53,104   
4        251715           54,104   
...         ...              ...   
14333    580467  105,21,61,54,53   
14334    593052      104,108,169   
14335    602620  170,168,0,53,61   
14336    602892           170,61   
14337    607092     105,108,0,61   

                                             ICD DISEASE  \
0      Pneumonia, unspecified organism,Urinary tract ...   
1      Essential Hypertension; malignant hypertension...   
2      Hypothyroidism, unspecified,Type 2 diabetes me...   
3      Urinary tract infection, site not specified,Th...   
4      Type 2 diabetes mellitus,Essential Hypertensio...   
...                                                  ...   
14333  Atherosclerotic heart disease of native corona...   
14334  Essential Hypertension; malignant hypertension...   
14335  Enlarged prostate,Disorder of kidney and urete...   
14336  Disorder of prostate, unspecified,Hyperlipidem...   
14337  Atherosclerotic heart disease of native corona...   

                                              claims_icd  
0                                  220945_113,220945_169  
1                        220946_104,220946_54,220946_113  
2                         230470_53,230470_54,230470_105  
3                        232051_169,232051_53,232051_104  
4                                   251715_54,251715_104  
...                                                  ...  
14333  580467_105,580467_21,580467_61,580467_54,58046...  
14334                   593052_104,593052_108,593052_169  
14335  602620_170,602620_168,602620_0,602620_53,60262...  
14336                               602892_170,602892_61  
14337           607092_105,607092_108,607092_0,607092_61  

[14338 rows x 4 columns]

In [101]:
transactions['icd'] = transactions['icdcategory'].apply(lambda t: t.split(','))
transactions = transactions['icd']
transactions

0                   [113, 169]
1               [104, 54, 113]
2                [53, 54, 105]
3               [169, 53, 104]
4                    [54, 104]
                 ...          
14333    [105, 21, 61, 54, 53]
14334          [104, 108, 169]
14335    [170, 168, 0, 53, 61]
14336                [170, 61]
14337        [105, 108, 0, 61]
Name: icd, Length: 14338, dtype: object

In [102]:
transaction_list = list(transactions)
print(transaction_list)

[['113', '169'], ['104', '54', '113'], ['53', '54', '105'], ['169', '53', '104'], ['54', '104'], ['97', '100'], ['166', '104'], ['61', '131'], ['104', '55'], ['104', '54'], ['15', '169', '0'], ['113', '55', '53'], ['104', '61'], ['105', '54'], ['108', '170'], ['284', '139'], ['48', '104'], ['104', '55'], ['53', '55'], ['104', '53'], ['104', '61'], ['0', '113'], ['169', '112'], ['108', '104'], ['104', '55'], ['130', '21', '54', '42', '105', '171', '124'], ['112', '105'], ['39', '171'], ['61', '53', '173', '131', '214', '168'], ['53', '105', '152', '61'], ['152', '105'], ['170', '104', '61'], ['169', '112', '10'], ['152', '156'], ['104', '156'], ['104', '55'], ['104', '61', '55'], ['104', '53'], ['167', '215', '104', '171'], ['169', '167'], ['128', '26'], ['116', '61', '104'], ['107', '54'], ['55', '61', '131'], ['164', '195', '113'], ['164', '61', '0'], ['10', '104'], ['168', '169'], ['61', '144', '55'], ['173', '171'], ['54', '104', '0', '46'], ['169', '53', '104'], ['277', '164', '54'

## One Hot Encoding

In [103]:
# Import the transaction encoder function from mlxtend
from mlxtend.preprocessing import TransactionEncoder

# Instantiate transaction encoder and identify unique items in transactions
encoder = TransactionEncoder().fit(transaction_list)

# One-hot encode transactions
onehot = encoder.transform(transaction_list)

# Convert one-hot encoded data to DataFrame
onehot = pd.DataFrame(onehot, columns = encoder.columns_)
onehot

0      1     10    100    102    103    104    105    106    107  \
0      False  False  False  False  False  False  False  False  False  False   
1      False  False  False  False  False  False   True  False  False  False   
2      False  False  False  False  False  False  False   True  False  False   
3      False  False  False  False  False  False   True  False  False  False   
4      False  False  False  False  False  False   True  False  False  False   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
14333  False  False  False  False  False  False  False   True  False  False   
14334  False  False  False  False  False  False   True  False  False  False   
14335   True  False  False  False  False  False  False  False  False  False   
14336  False  False  False  False  False  False  False  False  False  False   
14337   True  False  False  False  False  False  False   True  False  False   

       ...     87     88     89     90     91     93     95     97     98  \
0      ...  False  False  False  False  False  False  False  False  False   
1      ...  False  False  False  False  False  False  False  False  False   
2      ...  False  False  False  False  False  False  False  False  False   
3      ...  False  False  False  False  False  False  False  False  False   
4      ...  False  False  False  False  False  False  False  False  False   
...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
14333  ...  False  False  False  False  False  False  False  False  False   
14334  ...  False  False  False  False  False  False  False  False  False   
14335  ...  False  False  False  False  False  False  False  False  False   
14336  ...  False  False  False  False  False  False  False  False  False   
14337  ...  False  False  False  False  False  False  False  False  False   

          99  
0      False  
1      False  
2      False  
3      False  
4      False  
...      ...  
14333  False  
14334  False  
14335  False  
14336  False  
14337  False  

[14338 rows x 178 columns]

## Support Metric

**Support of ICD Categories**

In [104]:
onehot.mean()

0      0.058516
1      0.011717
10     0.022597
100    0.001186
102    0.000070
         ...   
93     0.001813
95     0.000139
97     0.002162
98     0.000976
99     0.001883
Length: 178, dtype: float64

In [105]:
support = pd.DataFrame(onehot.mean())
support.describe()

0
count  178.000000
mean     0.015126
std      0.052640
min      0.000070
25%      0.000349
50%      0.001151
75%      0.004865
max      0.415539

##Apriori

In [106]:
from mlxtend.frequent_patterns import apriori

frequent_itemsets = apriori(onehot, 
                            min_support = 0.0015, 
                            max_len = 3, 
                            use_colnames = True).sort_values('support',ascending=False)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

support        itemsets  length
74   0.415539            (61)       1
3    0.397684           (104)       1
70   0.231553            (54)       1
71   0.219556            (55)       1
134  0.148556       (61, 104)       2
..        ...             ...     ...
472  0.001534  (167, 54, 170)       3
454  0.001534  (61, 131, 167)       3
186  0.001534       (116, 54)       2
159  0.001534      (107, 170)       2
393  0.001534  (53, 105, 170)       3

[505 rows x 3 columns]

##Apriori results pruning

In [107]:
from mlxtend.frequent_patterns import association_rules

rules = association_rules(frequent_itemsets, 
                            metric = "confidence", 
                         	min_threshold = 0.65).sort_values('confidence',ascending=False)
rules

antecedents consequents  antecedent support  consequent support   support  \
9    (48, 215)        (61)            0.003836            0.415539  0.003208   
13  (215, 144)        (61)            0.001953            0.415539  0.001604   
15  (130, 168)        (61)            0.001953            0.415539  0.001534   
1   (215, 130)        (61)            0.015553            0.415539  0.012205   
3   (215, 169)        (61)            0.006765            0.415539  0.005301   
11  (215, 131)        (61)            0.002790            0.415539  0.002162   
4   (215, 170)        (61)            0.005998            0.415539  0.004533   
8   (215, 167)        (61)            0.004324            0.415539  0.003208   
10  (107, 215)        (61)            0.003069            0.415539  0.002232   
0        (215)        (61)            0.079230            0.415539  0.057470   
14  (167, 112)        (61)            0.002162            0.415539  0.001534   
5   (130, 112)        (61)            0.005859            0.415539  0.004115   
2   (130, 169)        (61)            0.015553            0.415539  0.010601   
6    (54, 112)        (61)            0.005440            0.415539  0.003627   
7   (215, 105)        (61)            0.004812            0.415539  0.003208   
12  (130, 166)        (61)            0.002720            0.415539  0.001813   

    confidence      lift  leverage  conviction  
9     0.836364  2.012719  0.001614    3.571705  
13    0.821429  1.976778  0.000793    3.272981  
15    0.785714  1.890831  0.000723    2.727484  
1     0.784753  1.888519  0.005742    2.715308  
3     0.783505  1.885515  0.002489    2.699653  
11    0.775000  1.865047  0.001003    2.597604  
4     0.755814  1.818876  0.002041    2.393506  
8     0.741935  1.785477  0.001411    2.264786  
10    0.727273  1.750191  0.000957    2.143023  
0     0.725352  1.745569  0.024546    2.128037  
14    0.709677  1.707847  0.000636    2.013143  
5     0.702381  1.690288  0.001680    1.963789  
2     0.681614  1.640313  0.004138    1.835701  
6     0.666667  1.604342  0.001366    1.753383  
7     0.666667  1.604342  0.001209    1.753383  
12    0.666667  1.604342  0.000683    1.753383

# MBA #2: Algorithms from twoardsdatascience.com

## Get Dummies

In [18]:
basket = claims_icdcombo[['claimcode','icdcategory']]
basket

claimcode icdcategory
7815      220945         113
7822      220945         169
7828      220946         104
7829      220946          54
7831      220946         113
...          ...         ...
382216    602892          61
382231    607092         105
382232    607092         108
382233    607092           0
382236    607092          61

[38603 rows x 2 columns]

In [65]:
# Convert ICD Category feature into indicators
basket_sparse = pd.get_dummies(basket, columns=['icdcategory']).set_index('claimcode')
basket_sparse

icdcategory_0  icdcategory_1  icdcategory_10  icdcategory_100  \
claimcode                                                                  
220945                 0              0               0                0   
220945                 0              0               0                0   
220946                 0              0               0                0   
220946                 0              0               0                0   
220946                 0              0               0                0   
...                  ...            ...             ...              ...   
602892                 0              0               0                0   
607092                 0              0               0                0   
607092                 0              0               0                0   
607092                 1              0               0                0   
607092                 0              0               0                0   

           icdcategory_102  icdcategory_103  icdcategory_104  icdcategory_105  \
claimcode                                                                       
220945                   0                0                0                0   
220945                   0                0                0                0   
220946                   0                0                1                0   
220946                   0                0                0                0   
220946                   0                0                0                0   
...                    ...              ...              ...              ...   
602892                   0                0                0                0   
607092                   0                0                0                1   
607092                   0                0                0                0   
607092                   0                0                0                0   
607092                   0                0                0                0   

           icdcategory_106  icdcategory_107  ...  icdcategory_87  \
claimcode                                    ...                   
220945                   0                0  ...               0   
220945                   0                0  ...               0   
220946                   0                0  ...               0   
220946                   0                0  ...               0   
220946                   0                0  ...               0   
...                    ...              ...  ...             ...   
602892                   0                0  ...               0   
607092                   0                0  ...               0   
607092                   0                0  ...               0   
607092                   0                0  ...               0   
607092                   0                0  ...               0   

           icdcategory_88  icdcategory_89  icdcategory_90  icdcategory_91  \
claimcode                                                                   
220945                  0               0               0               0   
220945                  0               0               0               0   
220946                  0               0               0               0   
220946                  0               0               0               0   
220946                  0               0               0               0   
...                   ...             ...             ...             ...   
602892                  0               0               0               0   
607092                  0               0               0               0   
607092                  0               0               0               0   
607092                  0               0               0               0   
607092                  0               0               0               0   

           icdcategory_93  icdcategory_95  icdcategory_97  icdcategory_98  \
clai

In [20]:
basket_sparse = basket_sparse.groupby('claimcode').sum().reset_index()
basket_sparse = pd.DataFrame(basket)
basket_sparse.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38603 entries, 7815 to 382236
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   claimcode    38603 non-null  object
 1   icdcategory  38603 non-null  object
dtypes: object(2)
memory usage: 904.8+ KB


## Apriori from mlxtend.frequent_patterns

In [21]:
!pip install mlxtend
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [22]:
itemsets = apriori(basket_sparse, use_colnames=True, min_support=0.0005)

ValueError: ignored

In [ ]:
frequent_icd_combo = apriori(sparse, min_support=0.03, use_colnames=True).sort_values('support',ascending=False).reset_index(drop=True)
frequent_icd_combo['length'] = frequent_icd_combo['itemsets'].apply(lambda x: len(x))
frequent_icd_combo